# 监控管理
management:
  # 端点控制
  endpoints:
    web:
      exposure:
        include: health,info

# spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1/moyu?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: shisong
    password: shisong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis配置 参考：https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/zh/index.html
mybatis:
  type-aliases-package: com.dodoyd.moyu.admin.domain
  mapper-locations: mapper/*.xml
  #  config-location: classpath:mybatis-config.xml
